### ISSUE TITLE
unordered names in professor dropdown

### ISSUE THREAD

**Issue by jluo3364** [DylanPina/RUCS-Hub#2]
When selecting the professor for a course, the names listed are not in any order, and it's a long list. It would help to order the names alphabetically by first or last name. Another feature would be to allow typing in the field to filter the names list.

**Comment by DylanPina** [comment]
That's a good idea, I'll add that now Thanks

**Comment by DylanPina** [comment]
I have sorted the professors by last name modified the input selection like you mentioned. Let me know what you think!

**Comment by jluo3364** [comment]
It works well :) I like that there's some tolerance for mistakes in spelling.
