### ISSUE TITLE
Non-custom 404 Error Pages

### ISSUE THREAD

**Issue by udaypatel1** [DylanPina/RUCS-Hub#5]
# Default Next.js 404 Page

**Problem**: From a user experience perspective, when a route that is not identified by the application is visited, the page throws a default Next.js 404 error.

![image](https://github.com/user-attachments/assets/8702b563-a1af-4b31-9746-6e49d10a5e24)

## Acceptance Criteria

Provide a custom 404 handler page that issues a modal warning, following the defined style of the application.

**Comment by DylanPina** [comment]
Great catch, I will work on this when I get the chance. Thank you for your feedback.

**Comment by udaypatel1** [comment]
Of course! @DylanPina, let me know if you need any dev effort with the application, this issue or others. The folder structure of the app is ✨exquisite✨

**Comment by DylanPina** [comment]
Thank you! I'll be uploading a roadmap of features I plan on adding to the project. You're also more than welcome to reach out with any ideas you have as well. You can also submit a PR for any changes/additions you'd like to implement.

**Comment by udaypatel1** [comment]
Awesome! Looking forward to build out features – think this app can really make an impact.

Also, the discord link might be expired: https://discord.gg/bc2yDRVs

**Comment by DylanPina** [comment]
Good catch, updating the link now
